service: cbf-meetup-api

provider:
  name: aws
  runtime: nodejs10.x

custom:
  region: eu-west-1
  stage: dev

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
  excludeDevDependencies: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline

